### ISSUE TITLE
gstreamer mpph265enc硬件加速失败，缺少某些 rk package

### ISSUE THREAD

**Issue by Ken-Vamrs** [radxa-pkg/vendor-profiles#7]
$: gst-launch-1.0 v4l2src device=/dev/video12 io-mode=4 min-buffers=64 ! video/x-raw,format=NV12,width=1280,height=720,framerate=30/1 ! mpph265enc bps=12000000 ! fakesink

WARNING: erroneous pipeline: no property "min-buffers" in element "v4l2src" 

尝试将rk相关的gst和v4l包之后可以正常运行
sudo apt install gir1.2-gst-plugins-bad-1.0/rk3588-bookworm-test gir1.2-gst-plugins-base-1.0/rk3588-bookworm-test gstreamer1.0-alsa-dbgsym/rk3588-bookworm-test gstreamer1.0-gl-dbgsym/rk3588-bookworm-test gstreamer1.0-gl/rk3588-bookworm-test gstreamer1.0-gtk3-dbgsym/rk3588-bookworm-test gstreamer1.0-gtk3/rk3588-bookworm-test gstreamer1.0-opencv-dbgsym/rk3588-bookworm-test gstreamer1.0-opencv/rk3588-bookworm-test gstreamer1.0-plugins-bad-apps-dbgsym/rk3588-bookworm-test gstreamer1.0-plugins-bad-apps/rk3588-bookworm-test gstreamer1.0-plugins-bad-dbgsym/rk3588-bookworm-test gstreamer1.0-plugins-bad/rk3588-bookworm-test gstreamer1.0-plugins-base-apps-dbgsym/rk3588-bookworm-test gstreamer1.0-plugins-base-apps/rk3588-bookworm-test gstreamer1.0-plugins-base-dbgsym/rk3588-bookworm-test gstreamer1.0-plugins-base/rk3588-bookworm-test gstreamer1.0-plugins-good-dbgsym/rk3588-bookworm-test gstreamer1.0-plugins-good/rk3588-bookworm-test gstreamer1.0-pulseaudio/rk3588-bookworm-test gstreamer1.0-qt5-dbgsym/rk3588-bookworm-test gstreamer1.0-qt5/rk3588-bookworm-test gstreamer1.0-qt6-dbgsym/rk3588-bookworm-test gstreamer1.0-qt6/rk3588-bookworm-test gstreamer1.0-rockchip1-dbgsym/rk3588-bookworm-test gstreamer1.0-tools-dbgsym/rk3588-bookworm-test gstreamer1.0-tools/rk3588-bookworm-test gstreamer1.0-wpe-dbgsym/rk3588-bookworm-test gstreamer1.0-wpe/rk3588-bookworm-test gstreamer1.0-x-dbgsym/rk3588-bookworm-test gstreamer1.0-x/rk3588-bookworm-test libgstreamer-gl1.0-0-dbgsym/rk3588-bookworm-test libgstreamer-gl1.0-0/rk3588-bookworm-test libgstreamer-opencv1.0-0-dbgsym/rk3588-bookworm-test libgstreamer-opencv1.0-0/rk3588-bookworm-test libgstreamer-plugins-bad1.0-0-dbgsym/rk3588-bookworm-test libgstreamer-plugins-bad1.0-0/rk3588-bookworm-test libgstreamer-plugins-bad1.0-dev/rk3588-bookworm-test libgstreamer-plugins-base1.0-0-dbgsym/rk3588-bookworm-test libgstreamer-plugins-base1.0-0/rk3588-bookworm-test libgstreamer-plugins-base1.0-dev/rk3588-bookworm-test libgstreamer1.0-0-dbgsym/rk3588-bookworm-test libgstreamer1.0-0/rk3588-bookworm-test libgstreamer1.0-dev-dbgsym/rk3588-bookworm-test libgstreamer1.0-dev/rk3588-bookworm-test gstreamer1.0-alsa/rk3588-bookworm-test 

sudo apt install libv4l-0-dbgsym/rk3588-bookworm-test libv4l-dev/rk3588-bookworm-test libv4l-rkmpp-dbgsym/rk3588-bookworm-test libv4l-rkmpp-dbgsym/rk3588-bookworm-test libv4l2rds0-dbgsym/rk3588-bookworm-test libv4lconvert0-dbgsym/rk3588-bookworm-test qv4l2-dbgsym/rk3588-bookworm-test qv4l2/rk3588-bookworm-test

**Comment by RadxaYuntian** [comment]
看看具体是哪个包需要替换，二分查找一下试试
